language: c++
sudo: required
os: linux
dist: xenial

addons:
  apt:
    packages:
      - libgsl-dev
      - libblas-dev

compiler:
  - g++

install: "libgsl-dev libblas-dev"
before_script:
  - cmake .

script: make
